name: EconomyDeBleu
version: '1.0-SNAPSHOT'
main: dev.o8o1o5.economyDeBleu.EconomyDeBleu
api-version: '1.21'
authors: [ o8o1o5 ]
description: Nickname change plugin
softdepend: [Vault]

commands:
  economy:
    description: Economy DeBleu plugin commands.
    usage: |
      /<command> help
      /<command> set <player> <amount>
      /<command> give <player> <amount>
      /<command> take <player> <amount>
      /<command> reset <player>
      /<command> unit <singular> <plural>
    permission: economydebleu.command.economy # 이 권한을 통해 모든 하위 명령어를 제어합니다.
    permission-message: You do not have permission to use this command.
  money:
    description: Check your balance.
    usage: /<command>
    permission: economydebleu.command.money # /money는 모든 플레이어가 사용 가능
    permission-message: You do not have permission to use this command.
  balance:
    description: Check your balance.
    usage: /<command>
    permission: economydebleu.command.balance # /balance도 모든 플레이어가 사용 가능
    permission-message: You do not have permission to use this command.
  pay:
    description: Pay money to another player.
    usage: /<command> <player> <amount>
    permission: economydebleu.command.pay # /pay도 모든 플레이어가 사용 가능
    permission-message: You do not have permission to use this command.

# Permissions (권한 정의)
permissions:
  economydebleu.command.economy: # eco 명령어의 기본 접근 권한
    description: Allows access to the base /economy command and its subcommands (set, give, take, reset, unit).
    default: op # 기본적으로 OP에게만 이 권한을 부여합니다.

  # 아래는 일반 플레이어가 사용할 수 있는 명령어들입니다.
  economydebleu.command.money:
    description: Allows a player to check their own money.
    default: true # 모든 플레이어에게 부여

  economydebleu.command.balance:
    description: Allows a player to check their own balance.
    default: true # 모든 플레이어에게 부여

  economydebleu.command.pay:
    description: Allows a player to pay money to another player.
    default: true # 모든 플레이어에게 부여

  # economydebleu.* 와일드카드 권한은 필요하다면 다시 추가할 수 있습니다.
  # economydebleu.command.economy.set 등 개별 하위 명령어 권한은 더 이상 필요 없습니다.